const C_MM_PER_NS = 299.792458;
const fields = ['type', 'frequencyGHz', 'substrateEr', 'substrateHeightMm', 'conductorThicknessMm', 'wireRadiusMm', 'groundLengthMm', 'groundWidthMm', 'feedGapMm', 'portImpedance'];

const round = (value, places = 3) => Number.isFinite(value) ? Number(value.toFixed(places)) : 0;
const vbaNumber = value => String(round(value, 4));

function readDesign() {
  return Object.fromEntries(fields.map(field => {
    const element = document.getElementById(field);
    return [field, field === 'type' ? element.value : Number(element.value)];
  }));
}

function estimateDimensions(design) {
  const lambda0 = C_MM_PER_NS / design.frequencyGHz;
  const dipoleLength = 0.48 * lambda0;
  const monopoleLength = 0.24 * lambda0;
  const patchWidth = C_MM_PER_NS / (2 * design.frequencyGHz) * Math.sqrt(2 / (design.substrateEr + 1));
  const erEff = (design.substrateEr + 1) / 2 + ((design.substrateEr - 1) / 2) / Math.sqrt(1 + 12 * design.substrateHeightMm / patchWidth);
  const deltaL = 0.412 * design.substrateHeightMm * ((erEff + 0.3) * (patchWidth / design.substrateHeightMm + 0.264)) / ((erEff - 0.258) * (patchWidth / design.substrateHeightMm + 0.8));
  const patchLength = C_MM_PER_NS / (2 * design.frequencyGHz * Math.sqrt(erEff)) - 2 * deltaL;
  return {
    lambda0: round(lambda0),
    dipoleArm: round(dipoleLength / 2),
    monopoleHeight: round(monopoleLength),
    patchLength: round(patchLength),
    patchWidth: round(patchWidth),
    feedInset: round(patchLength * 0.28),
  };
}

function generateVba(design) {
  const d = estimateDimensions(design);
  const header = `' Generated by EM-1D Antenna CST VBA Generator\n' &
    `' Target frequency: ${design.frequencyGHz} GHz\n` &
    `' Antenna type: ${design.type}\n`;
  const common = `Option Explicit\n\nSub Main()\n  Dim project As Object\n  Set project = Application.NewMWS\n\n  With Units\n    .Geometry "mm"\n    .Frequency "GHz"\n    .Time "ns"\n  End With\n\n  With Solver\n    .FrequencyRange "${vbaNumber(design.frequencyGHz * 0.6)}", "${vbaNumber(design.frequencyGHz * 1.4)}"\n  End With\n\n  With Material\n    .Reset\n    .Name "FR4_User_Tuned"\n    .Type "Normal"\n    .Epsilon "${vbaNumber(design.substrateEr)}"\n    .Mue "1"\n    .TanD "0.02"\n    .Create\n  End With\n\n`;

  if (design.type === 'patch') {
    const l = d.patchLength;
    const w = d.patchWidth;
    const gl = Math.max(design.groundLengthMm, l * 1.7);
    const gw = Math.max(design.groundWidthMm, w * 1.7);
    return `${header}${common}  ' Substrate\n  With Brick\n    .Reset\n    .Name "substrate"\n    .Component "antenna"\n    .Material "FR4_User_Tuned"\n    .Xrange "${vbaNumber(-gl / 2)}", "${vbaNumber(gl / 2)}"\n    .Yrange "${vbaNumber(-gw / 2)}", "${vbaNumber(gw / 2)}"\n    .Zrange "0", "${vbaNumber(design.substrateHeightMm)}"\n    .Create\n  End With\n\n  ' Ground plane\n  With Brick\n    .Reset\n    .Name "ground"\n    .Component "antenna"\n    .Material "PEC"\n    .Xrange "${vbaNumber(-gl / 2)}", "${vbaNumber(gl / 2)}"\n    .Yrange "${vbaNumber(-gw / 2)}", "${vbaNumber(gw / 2)}"\n    .Zrange "${vbaNumber(-design.conductorThicknessMm)}", "0"\n    .Create\n  End With\n\n  ' Rectangular patch\n  With Brick\n    .Reset\n    .Name "patch"\n    .Component "antenna"\n    .Material "PEC"\n    .Xrange "${vbaNumber(-l / 2)}", "${vbaNumber(l / 2)}"\n    .Yrange "${vbaNumber(-w / 2)}", "${vbaNumber(w / 2)}"\n    .Zrange "${vbaNumber(design.substrateHeightMm)}", "${vbaNumber(design.substrateHeightMm + design.conductorThicknessMm)}"\n    .Create\n  End With\n\n  ' Discrete feed from ground to inset point on patch\n  With DiscretePort\n    .Reset\n    .PortNumber "1"\n    .Type "SParameter"\n    .Impedance "${vbaNumber(design.portImpedance)}"\n    .SetP1 "False", "${vbaNumber(-l / 2 + d.feedInset)}", "0", "0"\n    .SetP2 "False", "${vbaNumber(-l / 2 + d.feedInset)}", "0", "${vbaNumber(design.substrateHeightMm)}"\n    .Create\n  End With\n\n  Boundary.Xmin "expanded open"\n  Boundary.Xmax "expanded open"\n  Boundary.Ymin "expanded open"\n  Boundary.Ymax "expanded open"\n  Boundary.Zmin "expanded open"\n  Boundary.Zmax "expanded open"\nEnd Sub\n`;
  }

  const length = design.type === 'dipole' ? d.dipoleArm : d.monopoleHeight;
  const zMin = design.type === 'dipole' ? -length - design.feedGapMm / 2 : 0;
  const zMax = length + design.feedGapMm / 2;
  const secondRadiator = design.type === 'dipole' ? `  With Cylinder\n    .Reset\n    .Name "radiator_negative"\n    .Component "antenna"\n    .Material "PEC"\n    .OuterRadius "${vbaNumber(design.wireRadiusMm)}"\n    .InnerRadius "0"\n    .Axis "z"\n    .Zrange "${vbaNumber(zMin)}", "${vbaNumber(-design.feedGapMm / 2)}"\n    .Xcenter "0"\n    .Ycenter "0"\n    .Create\n  End With\n\n` : `  With Brick\n    .Reset\n    .Name "ground"\n    .Component "antenna"\n    .Material "PEC"\n    .Xrange "${vbaNumber(-design.groundLengthMm / 2)}", "${vbaNumber(design.groundLengthMm / 2)}"\n    .Yrange "${vbaNumber(-design.groundWidthMm / 2)}", "${vbaNumber(design.groundWidthMm / 2)}"\n    .Zrange "${vbaNumber(-design.conductorThicknessMm)}", "0"\n    .Create\n  End With\n\n`;
  return `${header}${common}  ' Wire radiator generated as PEC cylinders. Adjust radius and length, then re-run CST.\n  With Cylinder\n    .Reset\n    .Name "radiator_positive"\n    .Component "antenna"\n    .Material "PEC"\n    .OuterRadius "${vbaNumber(design.wireRadiusMm)}"\n    .InnerRadius "0"\n    .Axis "z"\n    .Zrange "${vbaNumber(design.feedGapMm / 2)}", "${vbaNumber(zMax)}"\n    .Xcenter "0"\n    .Ycenter "0"\n    .Create\n  End With\n\n${secondRadiator}  With DiscretePort\n    .Reset\n    .PortNumber "1"\n    .Type "SParameter"\n    .Impedance "${vbaNumber(design.portImpedance)}"\n    .SetP1 "False", "0", "0", "${design.type === 'dipole' ? vbaNumber(-design.feedGapMm / 2) : '0'}"\n    .SetP2 "False", "0", "0", "${vbaNumber(design.feedGapMm / 2)}"\n    .Create\n  End With\n\n  Boundary.Xmin "expanded open"\n  Boundary.Xmax "expanded open"\n  Boundary.Ymin "expanded open"\n  Boundary.Ymax "expanded open"\n  Boundary.Zmin "expanded open"\n  Boundary.Zmax "expanded open"\nEnd Sub\n`;
}

function render() {
  const design = readDesign();
  const d = estimateDimensions(design);
  document.getElementById('lambda0').textContent = `${d.lambda0} mm`;
  document.getElementById('patchSize').textContent = `${d.patchLength} × ${d.patchWidth} mm`;
  document.getElementById('dipoleArm').textContent = `${d.dipoleArm} mm`;
  document.getElementById('monopoleHeight').textContent = `${d.monopoleHeight} mm`;
  document.getElementById('feedInset').textContent = `${d.feedInset} mm`;
  document.getElementById('vba').value = generateVba(design);
}

document.getElementById('controls').addEventListener('input', render);
document.getElementById('copy').addEventListener('click', () => navigator.clipboard.writeText(document.getElementById('vba').value));
document.getElementById('download').addEventListener('click', () => {
  const design = readDesign();
  const blob = new Blob([generateVba(design)], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = `${design.type}-${design.frequencyGHz}GHz-cst.vba`;
  anchor.click();
  URL.revokeObjectURL(url);
});
render();
